### ISSUE TITLE
Bugcrowd data missing

### ISSUE THREAD

**Issue by iangcarroll** [arkadiyt/bounty-targets#108]
Hi there, it seems like the data available for Bugcrowd in [bugcrowd_data.json](https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/master/data/bugcrowd_data.json) is missing quite a few programs, for example [Tesla](https://bugcrowd.com/tesla). I am not sure what is causing this but it does seem to result in a lot of missing entries. Sorry that I have not debugged it any further!

**Comment by arkadiyt** [comment]
Hey @iangcarroll, it looks like Bugcrowd changed their pagination parameters - it used to be e.g. `offset=25`, `offset=50`, etc, but they switched to using `page=1`, `page=2`. This has been broken since 4/6/22 and should be fixed now.

Thanks for flagging
