### ISSUE TITLE
bounty-targets-data not updated since 7 days

### ISSUE THREAD

**Issue by fgolshani** [arkadiyt/bounty-targets#118]
Hi ! on bounty-targets-data we can see last update is 8 days ago. The bot might be broken

**Comment by nil0x42** [comment]
Yes, was about to post the same issue. Bot definitely looks broken

**Comment by arkadiyt** [comment]
Hackerone's API is broken right now which is preventing me from fetching updated scopes from them - I'm trying to work with them on resolving the issue

**Comment by arkadiyt** [comment]
I've put in a hack to get this working again, but the hackerone_schema.graphql file will no longer be updated until Hackerone fixes the bug on their end

**Comment by arkadiyt** [comment]
Nevermind, I've gotten the schema working as well - thanks for your patience y'all
