### ISSUE TITLE
Intigriti and YesWeHack out_of_scopes not scraped

### ISSUE THREAD

**Issue by jamboro** [arkadiyt/bounty-targets#124]
Hi
It appears that both Intigriti, and YesWeHack out_of_scope is not being scraped, 
They are blank for all programs.
I wish I had enough knowledge in GO to resolve it, but I cannot :(
Thanks

**Comment by arkadiyt** [comment]
> YWH example:
> https://yeswehack.com/programs/muslim-pro

Muslim-pro and other programs look correctly scraped to me: https://github.com/arkadiyt/bounty-targets-data/blob/main/data/yeswehack_data.json#L894-L945.

> Intigriti example:
> https://app.intigriti.com/researcher/programs/infomaniak/infomaniak/detail

This is a private program - bounty-targets only lists public programs.

If you find any other examples feel free to comment below and I'll reopen the ticket

**Comment by jamboro** [comment]
1. Muslim-pro:
Where is the Out_of_scope ?!
In the link you sent, the out_of_scope array is empty..

Should be:
Out of scopes
support.muslimpro.com
translate.muslimpro.com
media.muslimpro.com
go.muslimpro.com

2, This is not a private program.
Anyway, all out_of_scope arrays in intigriti are empty, do you think there isn't a single program with out_of_scope on intigriti?

**Comment by jamboro** [comment]
"out_of_scope": [

      ]
    }
  },

**Comment by arkadiyt** [comment]
Sorry I misread the issue as being about the in-scope items, not the out of scope items

**Comment by arkadiyt** [comment]
Intigriti doesn't provide structured out-of-scope data, just a giant blob of text, so there's nothing I can do there.

YesWeHack out of scope items are now included, starting with this commit: https://github.com/arkadiyt/bounty-targets-data/commit/1bc50af11c8c5a7b4c7d09de3748ead81ee25390
