### ISSUE TITLE
Can you also add the OpenBugBounty bugbounty programs?

### ISSUE THREAD

**Issue by Root-FTW** [arkadiyt/bounty-targets#132]
Can you also add the OpenBugBounty bugbounty programs?

https://www.openbugbounty.org/bugbounty-list/

**Comment by arkadiyt** [comment]
This website looks fake? They list Ikea, Verizon, Berkeley, eBay, etc as customers but going to those websites has no mention of OpenBugBounty. Verizon and Ikea use Hackerone, eBay has a page asking to email them.

The OpenBugBounty page lists some tweet "testimonials" but clicking on those links there is no such tweet from those authors, or even proof that those authors work at those companies. 

The Verizon "testimonial" links to this account which has 0 followers and has never tweeted: https://twitter.com/RobMcGregor4

**Comment by Root-FTW** [comment]
mmm maybe you are new to the world of bugbounty, but OBB is the site where anyone can report XSS, it is only focused on XSS and the site is very famous, thousands of bughunters report there, personally this year I generated more than 5k USD reporting XSS, the way to do it is very simple.

Report XSS to as many sites as possible, OBB sends a technical report about the bug you reported and the owner of the website contacts you to explain more about the vulnerability, in the end they may give you some money or just a thank you or just nothing.

Ask other people about OBB, you will see that it is well known, only it is not very popular, since on this site you only report with the hope that they will give you something, since they are not obligated to give you something for your report.

**Comment by arkadiyt** [comment]
What does that have to do with fake testimonials?

**Comment by Root-FTW** [comment]
bro they are not false, reporting a security bug does not force the brand, for example ikea, to post a thank you from their main account, nobody does it, the one who attends to that is almost always the IT technicians, they are the ones who do the thank yous from their personal accounts, maybe that's why they don't have followers.

Ask the community of bughunters about OBB, you will see that it is a site with more years than HckerOne or Bugcrown
