### ISSUE TITLE
没有爬取到目标站点，请问是否可以添加修复一下

### ISSUE THREAD

**Issue by komomon** [arkadiyt/bounty-targets#135]
没有爬取到目标站点，只爬取到了title
![image](https://user-images.githubusercontent.com/52700174/222772193-aadcc13d-3bd0-42be-bc37-930f1088d1be.png)
![image](https://user-images.githubusercontent.com/52700174/222772402-5965e869-8ed2-40c9-a80e-e5cc679643e9.png)

**Comment by arkadiyt** [comment]
Should be fixed starting with https://github.com/arkadiyt/bounty-targets-data/commit/68b8f5e42fb38f431cfe76b20f978dfa1d51c447 I believe
