### ISSUE TITLE
bugcrowd bigcommerce star subs not fetched 

### ISSUE THREAD

**Issue by molitona** [arkadiyt/bounty-targets#138]
https://bugcrowd.com/bigcommerce -> *.bigcommerce.com	and *.bigcommerce.net

In https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/master/data/bugcrowd_data.json -> 

```
{
"type": "website",
"target": ""
},
{
"type": "website",
"target": ""
},
```

**Comment by arkadiyt** [comment]
This should be fixed
