### ISSUE TITLE
OOS domains improperly scraped

### ISSUE THREAD

**Issue by HolyBugx** [arkadiyt/bounty-targets#140]
Hi,

With the recent updates, the parser is now invalidly parsing the OOS domains.

*[Intigriti]*

There is not a single OOS domain for Intigriti: <https://github.com/arkadiyt/bounty-targets-data/blob/main/data/intigriti_data.json>

If you check any program, no valid OOS domain is scraped for it.

*[Bugcrowd]*

The OOS domains are improperly scraped with empty JSON objects. e.g.

* <https://bugcrowd.com/tripadvisor-bb-og>

and

* <https://github.com/arkadiyt/bounty-targets-data/blob/main/data/bugcrowd_data.json>

![image](https://user-images.githubusercontent.com/71842138/225859313-57ac473b-c70b-465d-82ee-d7ac1f81bc3a.png)

--

In addition, I believe this is one of the main commits that removed lots of OOS domains:

<https://github.com/arkadiyt/bounty-targets-data/commit/b559c43b924d87f76c18697ce204c8a9533a8f26>

Best regards,
HolyBugx

**Comment by HolyBugx** [comment]
Something else I just realized:

For some programs, the parser has removed the * and replaced it with http scheme.

Example: <https://bugcrowd.com/linktree-mbb-og>

```
*.filestack.com
*.freshdesk.com
*.blstr.xyz
*.blstr.co
```

![image](https://user-images.githubusercontent.com/71842138/225877691-200ba286-6f1a-4187-b013-50e0e68d54a9.png)

--

In addition, I believe this is one of the main commits that removed lots of OOS domains:

<https://github.com/arkadiyt/bounty-targets-data/commit/b559c43b924d87f76c18697ce204c8a9533a8f26>

Best regards,
HolyBugx

**Comment by arkadiyt** [comment]
> [Intigriti] There is not a single OOS domain for Intigriti: https://github.com/arkadiyt/bounty-targets-data/blob/main/data/intigriti_data.json

Intigriti does not provide out of scope domains in a structured way

> [Bugcrowd] The OOS domains are improperly scraped with empty JSON objects. e.g.

This should be fixed now
