### ISSUE TITLE
bounty-targets-data not updated since 2 weeks

### ISSUE THREAD

**Issue by patuuh** [arkadiyt/bounty-targets#141]
It seems that the bounty-targets-data is not updated in 2 weeks. Issues with platform api's?

**Comment by sumgr0** [comment]
Hi @arkadiyt,

Request your support in matter. Thanks for the amazing repo.

**Comment by arkadiyt** [comment]
@patuuh @sumgr0 this should be fixed via https://github.com/arkadiyt/bounty-targets/pull/144, there's a new commit on https://github.com/arkadiyt/bounty-targets-data/commit/a5f247413a34650c2fcbc55f1258c65af4a125cf. Sorry about the delay, life's been hectic lately

**Comment by sumgr0** [comment]
Thank you for the fix. Hope everything good at your end now :)

**Comment by gandhi3** [comment]
Thank you for the fix. Hope everything good at your end now :)
