### ISSUE TITLE
[Request] bugbounter.com Add

### ISSUE THREAD

**Issue by ramazansancar** [arkadiyt/bounty-targets#156]
- https://www.linkedin.com/company/bugbounter/

Program list:
- https://app.bugbounter.com/programs

**Comment by arkadiyt** [comment]
This looks like a small seed stage company and their program list does not even load:
<img width="1610" alt="Screenshot 2024-02-15 at 8 35 23 PM" src="https://github.com/arkadiyt/bounty-targets/assets/2279289/57d96d6d-e21c-4ca9-a2fe-cd17c1637a56">

I'd like to wait until they become more established

**Comment by ramazansancar** [comment]
Hi @arkadiyt,
The program list is visible only to logged in users.

![image](https://github.com/arkadiyt/bounty-targets/assets/8878055/ed6a7561-875d-4b81-a055-c1d62637d7a7)

Check here company info: https://www.google.com/search?&q=bugbounter&tbm=nws
