### ISSUE TITLE
24 bugcrowd public programs not catched

### ISSUE THREAD

**Issue by molitona** [arkadiyt/bounty-targets#162]
Hello, all 24 below public programs aren't fetched. I think it's something to have with the new url format engagements/xxxxxx maybe ?!

https://bugcrowd.com/engagements/odesk
https://bugcrowd.com/engagements/caffeine
https://bugcrowd.com/engagements/cloudinary
https://bugcrowd.com/engagements/elementor
https://bugcrowd.com/engagements/mettle
https://bugcrowd.com/engagements/ynab
https://bugcrowd.com/engagements/contrast-security
https://bugcrowd.com/engagements/dropbox
https://bugcrowd.com/engagements/rarible-ogmbb
https://bugcrowd.com/engagements/cfr
https://bugcrowd.com/engagements/bitstamp
https://bugcrowd.com/engagements/lime
https://bugcrowd.com/engagements/classdojo
https://bugcrowd.com/engagements/shipwire
https://bugcrowd.com/engagements/codeorg
https://bugcrowd.com/engagements/freedomofpress
https://bugcrowd.com/engagements/acorns
https://bugcrowd.com/engagements/foxycart
https://bugcrowd.com/engagements/tyler-tech-data-insights
https://bugcrowd.com/engagements/humblebundle
https://bugcrowd.com/engagements/planethosterinc
https://bugcrowd.com/engagements/whmcs
https://bugcrowd.com/engagements/directly
https://bugcrowd.com/engagements/immutable

**Comment by molitona** [comment]
+ bugcrowd scope file stopped being generated since 3 days

**Comment by arkadiyt** [comment]
> bugcrowd scope file stopped being generated since 3 days

It was generated an hour ago - if there are no updates to a file it just means the scopes haven't changed for that specific file

I'll take a look at engagements later tonight, I'm not sure I understand what the difference is between an engagement and a regular public program, is this documented somewhere?

**Comment by molitona** [comment]
> > bugcrowd scope file stopped being generated since 3 days
> 
> It was generated an hour ago - if there are no updates to a file it just means the scopes haven't changed for that specific file
> 
> I'll take a look at engagements later tonight, I'm not sure I understand what the difference is between an engagement and a regular public program, is this documented somewhere?

as far as i know it's modern structured form of a bugcrowd program. all ones will migrate to it in future. they call program as engagement now

**Comment by arkadiyt** [comment]
This data should be present starting with https://github.com/arkadiyt/bounty-targets-data/commit/b4f43bff8b706d064186962b7e3df141fb0e25db
