### ISSUE TITLE
hackerone "taking a break" programs not fetched

### ISSUE THREAD

**Issue by molitona** [arkadiyt/bounty-targets#163]
hello hackerone "taking a break" programs are not fetched like https://hackerone.com/caesars-digital?type=team 

![Screenshot from 2024-05-31 11-59-44](https://github.com/arkadiyt/bounty-targets/assets/35532337/1ac014f1-75bb-4a3d-8efc-6b49a0b91ce4)

now not in https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/master/data/hackerone_data.json

they are temporary paused often to high reports so they need time to handle while not receiving any new ones or sometimes on holidays programs take a break.

**Comment by arkadiyt** [comment]
This is intentional - if they're taking a break then I don't think they should continue to get scanner traffic

**Comment by molitona** [comment]
ok. closing
