### ISSUE TITLE
Uber Scopes Missing

### ISSUE THREAD

**Issue by t0xodile** [arkadiyt/bounty-targets#164]
Hello,
Pure coincidence that I checked for the Uber scope in the output and noticed that it isn't there.
Not sure why at all, it should include *.uber.com although it's possibly difficult to automate that due to how it appears?

**Comment by arkadiyt** [comment]
> although it's possibly difficult to automate that due to how it appears?

Precisely this, they have it formatted as free text in a sentence so it doesn't get parsed
