### ISSUE TITLE
add description field for each platfrom

### ISSUE THREAD

**Issue by savushkin-yauheni** [arkadiyt/bounty-targets#170]
Hi @arkadiyt 

What do you think about adding "description" field ( on any other name ) to the parser result?

What I mean, e.x. BC Binance program:

https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/bugcrowd_data.json
https://bugcrowd.com/engagements/binance

As you may see `*.binance.com` and `*.binance.us` are in Scope, but because they are links so in your `bugcrowd_data.json` we just see `www.binance.com` and `www.binance.us` .

So in general each platform has description or instruction field for such cases. Maybe it would be great if we add such field to the result? I could do it if you don't have time for this.

Regards

**Comment by arkadiyt** [comment]
I added the raw fields (name/uri/ipAddress) for engagements starting with https://github.com/arkadiyt/bounty-targets-data/commit/bc7520cc34168a19a86a3a1eb277c6d69161a27f, let me know if that works for you

**Comment by savushkin-yauheni** [comment]
Hi @arkadiyt 
Yep, it's perfect. Regards
