### ISSUE TITLE
Add Opire as a supported platform

### ISSUE THREAD

**Issue by nabby27** [arkadiyt/bounty-targets#172]
I'm the co-founder of Opire and we'd love for you to use our rewards on your project. All public rewards can be found at [https://app.opire.dev](https://app.opire.dev). If you need anything, feel free to contact me.

**Comment by arkadiyt** [comment]
Hey Ivan, this doesn't look like a bug bounty program?

**Comment by nabby27** [comment]
It's a bounty platform for issues, not just bugs.

**Comment by arkadiyt** [comment]
I think consumers of the dataset are looking for targets to pentest, not code to write
