### ISSUE TITLE
intigriti bug

### ISSUE THREAD

**Issue by savushkin-yauheni** [arkadiyt/bounty-targets#174]
Hi

Seems that smth has changed in intigriti parser and now it parses some OOS too.

https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/main/data/intigriti_data.json

```
*.cineramabios.nl
https://app.intigriti.com/programs/kinepolis/website/detail
```

```
it doesn't exist at all in policy
recon.periodandyear.stage.visma.com
https://app.intigriti.com/programs/visma/visma/detail
```

And much more strange examples

Regards

**Comment by arkadiyt** [comment]
Thanks for flagging, I can get this fixed tonight

**Comment by arkadiyt** [comment]
Should be fixed now, sorry about that
