### ISSUE TITLE
HackenProof BugFix

### ISSUE THREAD

**Issue by dorsky** [arkadiyt/bounty-targets#179]
Sup arkadiyt

If you will share IP address of your server, i will be able to whitelist you on our WAF, so the scanner will work again.
(btw, we have and API already, so maybe it can be improved)

dm me in twitter: `d0rsky`

**Comment by arkadiyt** [comment]
Thanks for reaching out

I'm running on the free tier of fly.io / don't have static ip addresses

> dm me in twitter: d0rsky

Do you have Signal?

**Comment by dorsky** [comment]
Yep, here it is: `d0rsky.01`
