### ISSUE TITLE
Public Program on Bugcrowd not in Repo

### ISSUE THREAD

**Issue by meme-lord** [arkadiyt/bounty-targets#185]
I noticed that the program https://bugcrowd.com/engagements/internetbrands-public is not included in the data despite being public, there must be a bug somewhere.

**Comment by meme-lord** [comment]
I've created a support ticket

**Comment by arkadiyt** [comment]
Hopefully you got a response from the team - I'm going to go ahead and close this since it isn't a bug with the project
