### ISSUE TITLE
Some Data Missed

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [arkadiyt/bounty-targets#188]
Hey, I noticed some data missed:

A.
post.ch exists in:
https://github.com/arkadiyt/bounty-targets-data/blob/main/data/yeswehack_data.json

"target": "(*.post.ch:80|*.post.ch:443) AND 194.41.128.0/17"

But not in wildcard list:
https://github.com/arkadiyt/bounty-targets-data/blob/main/data/wildcards.txt

B.
 *.doctolib.(fr|de|it|com|net)  exists in yeswehack but not in wildcards file.

C.
*.asana.plus exists in bugcrowd file but not in wildcards file. It seems in this case, you are extracting "target" but should be "name" ?

![image](https://github.com/user-attachments/assets/4a755822-be78-4f1e-9749-c6c8547df662)
![image](https://github.com/user-attachments/assets/2d248156-5625-4cb1-931e-4d6fea4bc3ee)

Thanks 🙏

**Comment by Sh4d0wHunt3rX** [comment]
I noticed the bug:

![image](https://github.com/user-attachments/assets/0419c4e7-ec9a-4d6f-9360-571027dc080a)
![image](https://github.com/user-attachments/assets/86f206d9-8ef7-4442-aca8-3c374d06b4a8)

This is the bug that I noticed in another script too:
https://github.com/sw33tLie/bbscope/issues/61

**Comment by arkadiyt** [comment]
The programs put the data in whatever format they want, it's relatively unstructured and there's no solution that fits everything
```
"target": "(.post.ch:80|.post.ch:443) AND 194.41.128.0/17"
*.doctolib.(fr|de|it|com|net)
```
these would be difficult to add programmatically, I don't want to manually cover all edge cases of what programs might submit into their target text field

> *.asana.plus exists in bugcrowd file but not in wildcards file. It seems in this case, you are extracting "target" but should be "name" ?

Asana does it this way, other programs depend on the name and not the target so if I swap it then I break those programs

The best solution is for you to parse the raw json file and directly search for the targets you want

**Comment by Sh4d0wHunt3rX** [comment]
Got it, thank you so much @arkadiyt 🙏

You are right and I finally decided to do as you said and used raw files. Thanks a lot for providing them.

I just noticed 1 thing, not sure if it's intentional or no.

Bugcrowd raw file does not include vpd programs, for example bluehost.in not exists in it. however, hackerone raw file includes vdp programs (not eligible for bounty). So, in the wildcards file, there are some eligible for bounty domains and also some not.

**Comment by arkadiyt** [comment]
Can you link the bugcrowd program which contains bluehost.in?

**Comment by Sh4d0wHunt3rX** [comment]
https://bugcrowd.com/engagements/newfold-bluehostindia-vdp

**Comment by arkadiyt** [comment]
This seems like the same issue as https://github.com/arkadiyt/bounty-targets/issues/185, that program does not show up in the public list

**Comment by Sh4d0wHunt3rX** [comment]
Ok, got it, thanks for checking that 🙏

**Comment by Sh4d0wHunt3rX** [comment]
@arkadiyt Hey, sorry to disturb you again Intigriti update was 5 days ago. For example "Axel Springer National Media & Tech" is a suspended program, but in the json file, it shows it as open

![image](https://github.com/user-attachments/assets/43bac874-da15-43ea-8da3-e89177c6fda7)

**Comment by arkadiyt** [comment]
This looks like an Intigriti bug again, they are themselves still returning Axel Springer as a non-suspended program on their public listings: https://www.intigriti.com/researchers/bug-bounty-programs

That page embeds a json object which contains all the program data, and it is saying Axel Springer has `status = 3 (open)`, not `status = 4 (suspended)`

**Comment by Sh4d0wHunt3rX** [comment]
@arkadiyt , I noticed some data also missed from Intigriti, for example "wolt" program not exists in your json, it also not exists in the link you provided, however, this script can somehow get that:

https://github.com/Osb0rn3/bugbounty-targets/blob/main/programs/intigriti.json

**Comment by arkadiyt** [comment]
That's not a public program. You can't access it here: https://github.com/Osb0rn3/bugbounty-targets/blob/main/programs/intigriti.json#L21276

<img width="692" alt="Screenshot 2024-12-30 at 8 54 52 AM" src="https://github.com/user-attachments/assets/f5df79fa-7876-4701-b1e3-021b205878e5" />
