### ISSUE TITLE
add public repository targets

### ISSUE THREAD

**Issue by gogo2464** [arkadiyt/bounty-targets#189]
Hello,

Thanks for the amazing tools!

I am wondering if we could have a list of git repos and git user + git group of compagnies that allow bug bounty please?

Best regards.

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the Hackerone class to collect and output git repository and user/group information for companies that allow bug bounties. This involves updating the GraphQL query to fetch the relevant data and adding a new method to process and return this information.

You can review changes in this commit: https://github.com/wwqwq2313/arkadiyt-bounty-targets-189/commit/411465bcc466e0c546b3003a7ad3a0935cb2b1a0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by gogo2464** [comment]
actually it is already possible in bash. it is a wontfix
