### ISSUE TITLE
Crawl community curated pages by using the "external" keyword

### ISSUE THREAD

**Issue by eraymitrani** [arkadiyt/bounty-targets#26]
This would really be useful to collect all the wildcard domains in one place for recon purposes. If you don't want to clutter the data you can create 2 new files for wildcard and regular external program scopes. I think it is a missed opportunity to not crawl the community curated pages. 

>If I knew ruby I would create a pull request sorry :/

https://github.com/arkadiyt/bounty-targets/blob/ae4a9562d2157ed5a8987b5e83c043a57163daaa/lib/bounty-targets/hackerone.rb#L38

**Comment by arkadiyt** [comment]
Hey, just to capture our discussion:

Sites that get on the domain list end up being subjected to a lot of scanner traffic, and the curated/external pages are added by members of the hackerone community, not the company themselves, so I'm reluctant to have them start showing up. Many of them don't have a disclosure process at all (https://hackerone.com/1_1_internet) and have not given consent to have security researchers poking their systems
