### ISSUE TITLE
Feature Request: Excluded URL's

### ISSUE THREAD

**Issue by JeffreyShran** [arkadiyt/bounty-targets#55]
Is it possible for this to be extended to include the excluded urls too?

**Comment by arkadiyt** [comment]
The excluded urls are included in the json files - did you have something else in mind?

**Comment by JeffreyShran** [comment]
No, I'm an idiot. Please ignore.

I only reviewed the txt files, not the JSON.

Really appreciate you pulling all of this together and making it public. :)
