### ISSUE TITLE
What do parentheses mean (in wildcards.txt)?

### ISSUE THREAD

**Issue by TheHackerDev** [arkadiyt/bounty-targets#58]
There are some domains in `wildcards.txt` that contain parentheses around wildcards (e.g `(*).endlcdn.site`, `(*).theendlessweb.com`). What do these mean?

Do they mean to include _only_ subdomains below those listed domains and not the parent domain (i.e. `abc.endlcdn.site`, but not `endlcdn.site`)?

Thank you.

**Comment by arkadiyt** [comment]
Hey @TheHackerDev, I would reach out to the program in question, it is a verbatim dump of their scopes: https://hackerone.com/endless_hosting
