### ISSUE TITLE
add other platforms like initigriti, yeswehack. 

### ISSUE THREAD

**Issue by 0xatul** [arkadiyt/bounty-targets#60]
I dont really know about what can you do on yeswehack but intigriti has an underlying api which can help you scrape the scope of a program: for example: 
``` 
https://api.intigriti.com/core/program/randstad/randstad
```
I think it follows this scheme: `https://api.intigriti.com/core/program/company_handle/program_name`

**Comment by arkadiyt** [comment]
Intigriti is now available here: https://github.com/arkadiyt/bounty-targets-data/blob/master/data/intigriti_data.json

**Comment by arkadiyt** [comment]
YesWeHack is now available here: https://github.com/arkadiyt/bounty-targets-data/blob/master/data/yeswehack_data.json
