### ISSUE TITLE
Support for Bugcrowd programs with multiple groups

### ISSUE THREAD

**Issue by iangcarroll** [arkadiyt/bounty-targets#79]
Hi there, I think the new Bugcrowd parsing in 0c33eccae0229c27af56e985377e79215661edc6 inadvertently prevented picking up programs which contain multiple in-scope groups, as it just pulls out the first parsed group for in-scope and out-of-scope and uses that. This results in programs like Arlo (https://bugcrowd.com/arlo) not having any domains, because they are all in the second in-scope group.

I think the fix is something like the following, to extract all groups and flatten them (non-recursively), but my Ruby is a little rusty and I had trouble getting this to work for every program. Hopefully someone knows the best syntax for this.

```rb
targets: {
  in_scope: scopes_to_hashes(content['groups'].find_all { |group| group['in_scope'] == true }.reduce([], :concat)),
  out_of_scope: scopes_to_hashes(content['groups'].find_all { |group| group['in_scope'] == false }.reduce([], :concat))
}
```

**Comment by arkadiyt** [comment]
Thanks for flagging this @iangcarroll - this was resolved via https://github.com/arkadiyt/bounty-targets/pull/80 and commit https://github.com/arkadiyt/bounty-targets-data/commit/9a49e5716593a06959487ef85725f6450040f897 contains the missing data
